language: generic
services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - ROS_REPO=ros
    - VERBOSE_OUTPUT=false
    - VERBOSE_TESTS=false
    - NOT_TEST_DOWNSTREAM=true
    - CMAKE_ARGS=-DCMAKE_BUILD_TYPE=Release
    - ADDITIONAL_DEBS='wget'
  matrix:
    - ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=file AFTER_SETUP_TARGET_WORKSPACE='wget -O - https://raw.githubusercontent.com/mojin-robotics/realsense/realsense_substitute/realsense_camera/patch/patch_docker.sh | bash'
    - ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=debian AFTER_SETUP_TARGET_WORKSPACE='wget -O - https://raw.githubusercontent.com/mojin-robotics/realsense/realsense_substitute/realsense_camera/patch/patch_docker.sh | bash'
    - ROS_DISTRO=melodic UPSTREAM_WORKSPACE=file
    - ROS_DISTRO=melodic UPSTREAM_WORKSPACE=debian
matrix:
  allow_failures:
    - env: ROS_DISTRO=melodic UPSTREAM_WORKSPACE=debian
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh